### ISSUE TITLE
rebar2 compatibility

### ISSUE THREAD

**Issue by lrascao** [cabol/shards#12]
Projects that still rely on rebar2 are unable to build `shards` (example on Mac):
`cc /Users/luis.rascao/Projects/shards/c_src/jumping_hash.o -arch x86_64  -shared -L /Users/luis.rascao/Projects/erlang/17.4-hipe/lib/erl_interface-3.7.20/lib -lerl_interface -lei -o /Users/luis.rascao/Projects/shards/c_src/../priv/jumping_hash.so
Undefined symbols for architecture x86_64:
  "_enif_get_uint", referenced from:
      _compute in jumping_hash.o
  "_enif_get_ulong", referenced from:
      _compute in jumping_hash.o
  "_enif_make_badarg", referenced from:
      _compute in jumping_hash.o
  "_enif_make_int", referenced from:
      _compute in jumping_hash.o
`

rebar2 compat would help adoption

**Comment by cabol** [comment]
@lrascao totally agree with you, I'll take a look at it ASAP, thanks!!!

**Comment by cabol** [comment]
@lrascao could you give me more details about your scenario? E.g.: I suppose you're using `shards` as dependency of other project which uses rebar2, because if this is the case, I did a couple of examples and they worked ok to me – I usually use Erlang 18, but I did the test with 17 and it worked, so I'm not sure what might be the cause of the error.

**Comment by lrascao** [comment]
@cabol, you are right indeed, i tracked down this issue to an apparent rebar2 regression (i was using the latest rebar2 from the master branch), it worked fine with the previous stable, closing this one
thanks!
