### ISSUE TITLE
LRU Feature may be 

### ISSUE THREAD

**Issue by grizzly-monkey** [cabol/shards#29]
Can we have a feature of autodeleting record if its retrieved for X amount of time  making free space for other objects to use the space ? something like LRU logic

**Comment by cabol** [comment]
I know it might be useful, but I'm not sure if it make sense add this feature to `shards`, because the original idea is to be compatible with `ets`, in other words: `shards` = `ets` + sharding support (out-of-box). Keeping that in mind, `shards` is as simple as `ets`, only provides the storage and solves the problem of lock contention to be able to scale-out. A feature like LRU sounds more like a Cache, and it can be implemented fairly easy using shards – either a local Cahe or a distributed one. So I think it would be nice to have another project, implementing those kind of features you mentioned, that would be a nice contrubution :) 

Look, this is an existing Cache example (very simple and still WIP): [Cacherl](https://github.com/ferigis/cacherl)

Let me know your thoughts, stay tuned!

Thanks!!!

**Comment by grizzly-monkey** [comment]
make sense ill try to implement something custom on top of shards. 
Great work !!! with shrads @cabol
